spring.application.name=CodeCollabPlatform
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.session.store-type=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

application.security.jwt.secret=${JWT_SECRET}


frontend.url=${FRONTEND_URL}

judge0.api.url=https://judge0-ce.p.rapidapi.com/submissions?base64_encoded=false&wait=true
judge0.api.key=${JUDGE0_API_KEY}
judge0.api.host=judge0-ce.p.rapidapi.com


